

import Head from "next/head";
import Card from "../../components/Cards";
import SideBar from "@/components/SideBar";


const Profile = () => {
  return (


    <div className="flex">
    <div className="w-64">
      <SideBar />
    </div>
    <div className="flex-grow flex justify-center items-center">
      <Head>
        <title>Modern Card</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pro.ico" />
      </Head>
      <div className="bg-hero w-full h-screen bg-cover bg-fixed flex justify-center items-center">
        <Card />
      </div>
    </div>
  </div>


  );
}

export default Profile